server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/caihongwei/Documents/Development/MyGit/sora-repo
          repos:
            development:
              pattern:
                - */staging
              uri: git@git.oschina.net:cai2008/sora-repo.git
              hostKeyAlgorithm: ecdsa-sha2-nistp256
#          basedir: cloudconfig

security:
  user:
    name: hong  # 默认user
    password: 111111 # 不设置密码时，在启动时会随机生成一个密码，log级别info打印

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@127.0.0.1:8761/eureka

logging:
  config: classpath:config/log4j2-spring.xml

---
spring:
  profiles: test

---
spring:
  profiles: product