server:
  port: 10000

sidecar:
  port: 8000
#  health-uri: http://localhost:8000/health.json

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: gateway
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/