server:
  port: 8080

eureka:
  instance:
#    hostname: server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

mybatis:
  type-aliases-package: com.hong.server.domain
  mapper-locations: classpath*:com/hong/server/**/*Mapper.xml